include: ../../analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    public_member_api_docs: false
    diagnostic_describe_all_properties: false
    avoid_redundant_argument_values: false
    discarded_futures: false
    always_specify_types: false
    specify_nonobvious_local_variable_types: false
    avoid_catches_without_on_clauses: false
    sort_pub_dependencies: false
