name: storage_interface
description: Storage interfaces for TinyTree
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  domain:
    path: ../domain

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
